# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'uploads/product_image', verbose_name='im\xe1gen')),
                ('published', models.BooleanField(default=True, verbose_name='publicado')),
                ('position', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, verbose_name='posici\xf3n')),
            ],
            options={
                'verbose_name': 'im\xe1gen de producto',
                'verbose_name_plural': 'im\xe1genes de productos',
            },
        ),
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'categor\xeda del producto', 'verbose_name_plural': 'categor\xedas de los productos'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contacto', 'verbose_name_plural': 'contactos'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'pregunta frecuente', 'verbose_name_plural': 'preguntas frecuentes'},
        ),
        migrations.AlterModelOptions(
            name='imagebanner',
            options={'verbose_name': 'im\xe1gen banner', 'verbose_name_plural': 'im\xe1genes banner'},
        ),
        migrations.AlterModelOptions(
            name='imagecategorybanner',
            options={'verbose_name': 'lugar del banner', 'verbose_name_plural': 'lugares de los banners'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='productgender',
            options={'verbose_name': 'g\xe9nero del producto', 'verbose_name_plural': 'g\xe9neros de los productos'},
        ),
        migrations.AlterField(
            model_name='imagebanner',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='nombre de la im\xe1gen'),
        ),
        migrations.AlterField(
            model_name='imagebanner',
            name='product_gender',
            field=models.CharField(choices=[(b'S', b'Peque\xc3\xb1o'), (b'M', b'Mediano'), (b'B', b'Grande')], default=b'M', max_length=1, verbose_name='tama\xf1o de la im\xe1gen'),
        ),
        migrations.AlterField(
            model_name='productgender',
            name='product_gender',
            field=models.CharField(choices=[(b'M', b'Mujer'), (b'H', b'Hombre'), (b'U', b'Unisex')], default=b'U', max_length=1, verbose_name='g\xe9nero del producto'),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.Product'),
        ),
    ]
