# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180320_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebanner',
            name='image',
            field=models.ImageField(default=None, upload_to=b'uploads/banner_image', verbose_name='imagen del banner'),
            preserve_default=False,
        ),
    ]
