# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_imagebanner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagebanner',
            old_name='product_gender',
            new_name='image_size',
        ),
    ]
