# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180320_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebanner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre de la im\xe1gen'),
        ),
    ]
