# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180322_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebanner',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.ImageCategoryBanner', verbose_name='lugar'),
        ),
    ]
