# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180322_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgender',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_gender',
            field=models.CharField(choices=[(b'M', b'Mujer'), (b'H', b'Hombre'), (b'U', b'Unisex')], default=b'U', max_length=1, verbose_name='g\xe9nero del producto'),
        ),
        migrations.DeleteModel(
            name='ProductGender',
        ),
    ]
