# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20180322_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='nombre'),
        ),
    ]
