# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 03:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180322_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='read',
            field=models.BooleanField(default=False, verbose_name='leido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='submited_on',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha y hora'),
        ),
    ]
