# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20180323_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproduct',
            name='image_size',
            field=models.CharField(choices=[(b'M', b'Celular'), (b'S', b'Normal')], default=b'S', max_length=1, verbose_name='tama\xf1o de la im\xe1gen'),
        ),
    ]
