# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_imageproduct_image_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha y hora'),
        ),
    ]
