# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20180405_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AlterField(
            model_name='imagebanner',
            name='image_size',
            field=models.CharField(choices=[(b'S', b'Peque\xc3\xb1o'), (b'M', b'Mediano'), (b'B', b'Grande')], default=b'M', max_length=1, verbose_name='tama\xf1o de la im\xe1gen'),
        ),
    ]
